#!/usr/local/bin/python3

import json
from json_flatten import flatten

with open('dataset.json') as f:
    d = json.load(f)

flat_json = flatten(d)

print(flat_json)
# {
#   "programs.[0].season": "1842-43",
#   "programs.[0].orchestra": "New York Philharmonic",
#   "programs.[0].concerts.[0].Date": "1842-12-07T05:00:00Z",
#   "programs.[0].concerts.[0].eventType": "Subscription Season",
#   "programs.[0].concerts.[0].Venue": "Apollo Rooms",
#   "programs.[0].concerts.[0].Location": "Manhattan, NY",
#   "programs.[0].concerts.[0].Time": "8:00PM",
#   "programs.[0].programID": "3853",
#   "programs.[0].works.[0].workTitle": "SYMPHONY NO. 5 IN C MINOR, OP.67",
#   "programs.[0].works.[0].conductorName": "Hill, Ureli Corelli",
#   "programs.[0].works.[0].ID": "52446*",
#   "programs.[0].works.[0].soloists$emptylist": "[]",
#   "programs.[0].works.[0].composerName": "Beethoven,  Ludwig  van",
#   "programs.[0].works.[1].workTitle": "OBERON",
#   "programs.[0].works.[1].composerName": "Weber,  Carl  Maria Von",
#   "programs.[0].works.[1].conductorName": "Timm, Henry C.",
#   "programs.[0].works.[1].ID": "8834*4",
#   "programs.[0].works.[1].soloists.[0].soloistName": "Otto, Antoinette",
#   "programs.[0].works.[1].soloists.[0].soloistRoles": "S",
#   "programs.[0].works.[1].soloists.[0].soloistInstrument": "Soprano",
#   "programs.[0].works.[1].movement": "'Ozean, du Ungeheuer' (Ocean, thou mighty monster), Reiza (Scene and Aria), Act II",
#   "programs.[0].works.[2].workTitle": "QUINTET, PIANO, D MINOR, OP. 74",
#   "programs.[0].works.[2].ID": "3642*",
#   "programs.[0].works.[2].soloists.[0].soloistName": "Scharfenberg, William",
#   "programs.[0].works.[2].soloists.[0].soloistRoles": "A",
#   "programs.[0].works.[2].soloists.[0].soloistInstrument": "Piano",
#   "programs.[0].works.[2].soloists.[1].soloistName": "Hill, Ureli Corelli",
#   "programs.[0].works.[2].soloists.[1].soloistRoles": "A",
#   "programs.[0].works.[2].soloists.[1].soloistInstrument": "Violin",
#   "programs.[0].works.[2].soloists.[2].soloistName": "Derwort, G. H.",
#   "programs.[0].works.[2].soloists.[2].soloistRoles": "A",
#   "programs.[0].works.[2].soloists.[2].soloistInstrument": "Viola",
#   "programs.[0].works.[2].soloists.[3].soloistName": "Boucher, Alfred",
#   "programs.[0].works.[2].soloists.[3].soloistRoles": "A",
#   "programs.[0].works.[2].soloists.[3].soloistInstrument": "Cello",
#   "programs.[0].works.[2].soloists.[4].soloistName": "Rosier, F. W.",
#   "programs.[0].works.[2].soloists.[4].soloistRoles": "A",
#   "programs.[0].works.[2].soloists.[4].soloistInstrument": "Contrabass",
#   "programs.[0].works.[2].composerName": "Hummel,  Johann",
#   "programs.[0].works.[3].interval": "Intermission",
#   "programs.[0].works.[3].ID": "0*",
#   "programs.[0].works.[3].soloists$emptylist": "[]",
#   "programs.[0].works.[4].workTitle": "OBERON",
#   "programs.[0].works.[4].composerName": "Weber,  Carl  Maria Von",
#   "programs.[0].works.[4].conductorName": "Etienne, Denis G.",
#   "programs.[0].works.[4].ID": "8834*3",
#   "programs.[0].works.[4].soloists$emptylist": "[]",
#   "programs.[0].works.[4].movement": "Overture",
#   "programs.[0].works.[5].workTitle": "ARMIDA",
#   "programs.[0].works.[5].composerName": "Rossini,  Gioachino",
#   "programs.[0].works.[5].conductorName": "Timm, Henry C.",
#   "programs.[0].works.[5].ID": "8835*1",
#   "programs.[0].works.[5].soloists.[0].soloistName": "Otto, Antoinette",
#   "programs.[0].works.[5].soloists.[0].soloistRoles": "S",
#   "programs.[0].works.[5].soloists.[0].soloistInstrument": "Soprano",
#   "programs.[0].works.[5].soloists.[1].soloistName": "Horn, Charles Edward",
#   "programs.[0].works.[5].soloists.[1].soloistRoles": "S",
#   "programs.[0].works.[5].soloists.[1].soloistInstrument": "Tenor",
#   "programs.[0].works.[5].movement": "Duet",
#   "programs.[0].works.[6].workTitle": "FIDELIO, OP. 72",
#   "programs.[0].works.[6].composerName": "Beethoven,  Ludwig  van",
#   "programs.[0].works.[6].conductorName": "Timm, Henry C.",
#   "programs.[0].works.[6].ID": "8837*6",
#   "programs.[0].works.[6].soloists.[0].soloistName": "Horn, Charles Edward",
#   "programs.[0].works.[6].soloists.[0].soloistRoles": "S",
#   "programs.[0].works.[6].soloists.[0].soloistInstrument": "Tenor",
#   "programs.[0].works.[6].movement": "'In Des Lebens Fruhlingstagen...O spur ich nicht linde,' Florestan (aria)",
#   "programs.[0].works.[7].workTitle": "ABDUCTION FROM THE SERAGLIO,THE, K.384",
#   "programs.[0].works.[7].composerName": "Mozart,  Wolfgang  Amadeus",
#   "programs.[0].works.[7].conductorName": "Timm, Henry C.",
#   "programs.[0].works.[7].ID": "8336*4",
#   "programs.[0].works.[7].soloists.[0].soloistName": "Otto, Antoinette",
#   "programs.[0].works.[7].soloists.[0].soloistRoles": "S",
#   "programs.[0].works.[7].soloists.[0].soloistInstrument": "Soprano",
#   "programs.[0].works.[7].movement": "'Ach Ich liebte,' Konstanze (aria)",
#   "programs.[0].works.[8].workTitle": "OVERTURE NO. 1, D MINOR, OP. 38",
#   "programs.[0].works.[8].conductorName": "Timm, Henry C.",
#   "programs.[0].works.[8].ID": "5543*",
#   "programs.[0].works.[8].soloists$emptylist": "[]",
#   "programs.[0].works.[8].composerName": "Kalliwoda,  Johann  W.",
#   "programs.[0].id": "38e072a7-8fc9-4f9a-8eac-3957905c0002",
#   "programs.[1].season": "1842-43",
#   "programs.[1].orchestra": "New York Philharmonic",
#   "programs.[1].concerts.[0].Date": "1843-02-18T05:00:00Z",
#   "programs.[1].concerts.[0].eventType": "Subscription Season",
#   "programs.[1].concerts.[0].Venue": "Apollo Rooms",
#   "programs.[1].concerts.[0].Location": "Manhattan, NY",
#   "programs.[1].concerts.[0].Time": "8:00PM",
#   "programs.[1].programID": "5178",
#   "programs.[1].works.[0].workTitle": "SYMPHONY NO. 3 IN E FLAT MAJOR, OP. 55 (EROICA)",
#   "programs.[1].works.[0].conductorName": "Hill, Ureli Corelli",
#   "programs.[1].works.[0].ID": "52437*",
#   "programs.[1].works.[0].soloists$emptylist": "[]",
#   "programs.[1].works.[0].composerName": "Beethoven,  Ludwig  van",
#   "programs.[1].works.[1].workTitle": "I PURITANI",
#   "programs.[1].works.[1].composerName": "Bellini,  Vincenzo",
#   "programs.[1].works.[1].conductorName": "Hill, Ureli Corelli",
#   "programs.[1].works.[1].ID": "8838*2",
#   "programs.[1].works.[1].soloists.[0].soloistName": "Otto, Antoinette",
#   "programs.[1].works.[1].soloists.[0].soloistRoles": "S",
#   "programs.[1].works.[1].soloists.[0].soloistInstrument": "Soprano",
#   "programs.[1].works.[1].movement": "Elvira (aria): 'Qui la voce...Vien, diletto'",
#   "programs.[1].works.[2].workTitle": "CELEBRATED ELEGIE",
#   "programs.[1].works.[2].conductorName": "Hill, Ureli Corelli",
#   "programs.[1].works.[2].ID": "3659*",
#   "programs.[1].works.[2].soloists.[0].soloistName": "Boucher, Alfred",
#   "programs.[1].works.[2].soloists.[0].soloistRoles": "S",
#   "programs.[1].works.[2].soloists.[0].soloistInstrument": "Cello",
#   "programs.[1].works.[2].composerName": "Romberg,  Bernhard",
#   "programs.[1].works.[3].interval": "Intermission",
#   "programs.[1].works.[3].ID": "0*",
#   "programs.[1].works.[3].soloists$emptylist": "[]",
#   "programs.[1].works.[4].workTitle": "WILLIAM TELL",
#   "programs.[1].works.[4].composerName": "Rossini,  Gioachino",
#   "programs.[1].works.[4].conductorName": "Alpers, William",
#   "programs.[1].works.[4].ID": "8839*2",
#   "programs.[1].works.[4].soloists$emptylist": "[]",
#   "programs.[1].works.[4].movement": "Overture",
#   "programs.[1].works.[5].workTitle": "STABAT MATER",
#   "programs.[1].works.[5].composerName": "Rossini,  Gioachino",
#   "programs.[1].works.[5].conductorName": "Alpers, William",
#   "programs.[1].works.[5].ID": "53076*2",
#   "programs.[1].works.[5].soloists.[0].soloistName": "Otto, Antoinette",
#   "programs.[1].works.[5].soloists.[0].soloistRoles": "S",
#   "programs.[1].works.[5].soloists.[0].soloistInstrument": "Soprano",
#   "programs.[1].works.[5].movement": "Inflammatus et Accensus (Aria with Chorus)",
#   "programs.[1].works.[6].workTitle": "CONCERTO, PIANO, A-FLAT MAJOR, OP. 113",
#   "programs.[1].works.[6].composerName": "Hummel,  Johann",
#   "programs.[1].works.[6].conductorName": "Alpers, William",
#   "programs.[1].works.[6].ID": "51568*2",
#   "programs.[1].works.[6].soloists.[0].soloistName": "Timm, Henry C.",
#   "programs.[1].works.[6].soloists.[0].soloistRoles": "S",
#   "programs.[1].works.[6].soloists.[0].soloistInstrument": "Piano",
#   "programs.[1].works.[6].movement": "Romanza: Larghetto con moto",
#   "programs.[1].works.[7].workTitle": "CONCERTO, PIANO, A-FLAT MAJOR, OP. 113",
#   "programs.[1].works.[7].composerName": "Hummel,  Johann",
#   "programs.[1].works.[7].conductorName": "Alpers, William",
#   "programs.[1].works.[7].ID": "51568*3",
#   "programs.[1].works.[7].soloists.[0].soloistName": "Timm, Henry C.",
#   "programs.[1].works.[7].soloists.[0].soloistRoles": "S",
#   "programs.[1].works.[7].soloists.[0].soloistInstrument": "Piano",
#   "programs.[1].works.[7].movement": "Rondo alla spagniola: Allegro moderato",
#   "programs.[1].works.[8].workTitle": "FREISCHUTZ, DER",
#   "programs.[1].works.[8].composerName": "Weber,  Carl  Maria Von",
#   "programs.[1].works.[8].conductorName": "Alpers, William",
#   "programs.[1].works.[8].ID": "6709*16",
#   "programs.[1].works.[8].soloists$emptylist": "[]",
#   "programs.[1].works.[8].movement": "Overture",
#   "programs.[1].id": "c7b2b95c-5e0b-431c-a340-5b37fc860b34"
# }